version: "3.9"
services:
  jenkins: 
    image: jenkins/jenkins
    container_name: jenkins-master
    ports: 
      - "8080:8080"
      - "50000:50000"
    volumes:
        - jenkins:/var/jenkins_home  
  jenkins-agent:
    image: jenkins/ssh-agent:alpine
    container_name: ssh-agent
    ports: 
      - "22:22"
    environment: 
      - "JENKINS_AGENT_SSH_PUBKEY=${pub-key}"
